import { Metadata } from "next";

const POST_URL = "https://keiretsu-frame-airdrop.vercel.app/api/frame";
const IMG_URL = "https://keiretsu-frame-airdrop.vercel.app/standquiz.png";
const Q1_URL = "https://keiretsu-frame-airdrop.vercel.app/api/q1";

console.log("posturl", POST_URL);
const frameMetadata = {
  "fc:frame": "vNext",
  "fc:frame:image": IMG_URL,
  "fc:frame:button:1": "Begin Quiz",
  "fc:frame:post_url": Q1_URL,
};

export const metadata: Metadata = {
  title: "Stand With Crypto!",
  description: "Generated by Ken",
  openGraph: {
    title: "Stand w/ Crypto Airdrop",
    images: [IMG_URL],
  },
  other: {
    ...frameMetadata,
  },
};

export default function Home() {
  return (
    <main>
      <h1>Stand With Crypto Frame Quiz</h1>
      <p>
        To participate, please visit{" "}
        <a href="https://www.standwithcrypto.org/">Stand with Crypto</a>.
      </p>
    </main>
  );
}
